services:
  torrra:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: torrra
    stdin_open: true
    tty: true
    volumes:
      - torrra_config:/root/.config
      # - ./docker_downloads:/root/Downloads
    develop:
      watch:
        - action: sync
          path: ./src
          target: /code/src

  # ========== INDEXERS ==========
  jackett:
    image: linuxserver/jackett
    container_name: jackett
    ports:
      - "9118:9117"
    volumes:
      - jackett_config:/config
    restart: unless-stopped

volumes:
  torrra_config:
  jackett_config:
