name: Publish to AUR

on:
  push:
    tags:
      - "v*"

jobs:
  aur:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set env vars
        run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_ENV

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.AUR_SSH_PRIVATE_KEY }}

      - name: Add AUR to known_hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan aur.archlinux.org >> ~/.ssh/known_hosts
          chmod 600 ~/.ssh/known_hosts

      - name: Push torrra-bin
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git clone ssh://aur@aur.archlinux.org/torrra-bin.git
          cd torrra-bin

          sed -i "s/^pkgver=.*/pkgver=${{ env.VERSION }}/" PKGBUILD
          sed -i "s/^pkgrel=.*/pkgrel=1/" PKGBUILD
          updpkgsums
          makepkg --printsrcinfo > .SRCINFO

          git add PKGBUILD .SRCINFO
          git diff --staged --quiet || git commit -m "chore: release v${{ env.VERSION }}"
          git push

      - name: Push torrra (source build)
        run: |
          git clone ssh://aur@aur.archlinux.org/torrra.git
          cd torrra

          sed -i "s/^pkgver=.*/pkgver=${{ env.VERSION }}/" PKGBUILD
          sed -i "s/^pkgrel=.*/pkgrel=1/" PKGBUILD
          updpkgsums
          makepkg --printsrcinfo > .SRCINFO

          git add PKGBUILD .SRCINFO
          git diff --staged --quiet || git commit -m "chore: release v${{ env.VERSION }}"
          git push
